version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      - ./back/.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  back:
    container_name: back
    build: ./back
    ports:
      - "3001:3000"
    volumes:
      - ./back:/usr/src/app
    env_file:
      - ./back/.env
    depends_on:
      - mysql

  front:
    container_name: front
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
    depends_on:
      - back

volumes:
  mysql-data:
